[project]
name = "jupyter-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "imbalanced-learn>=0.12.4",
    "kagglehub[pandas-datasets]>=0.3.13",
    "matplotlib>=3.9.4",
    "pyqt6>=6.10.0",
    "shap==0.35",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
